### ISSUE TITLE
General upgrade

### ISSUE THREAD

**Issue by yoglo** [bihealth/WiPP#3]
Requires general upgrade to support Ubuntu 20
List of dependencies have been already cut down in the dev branch, Bioconda and snakemake also need to be upgraded (activation of bioconda environment within snakemake is deprecated).

**Comment by ninathiessen** [comment]
This issue was resolved with the updates commit:
https://github.com/bihealth/WiPP/commit/8bcd07221569606d59583986dd0b007cc7ceecfb

I tested the code in the above commit successfully on the following systems:
* Ubuntu 16, conda 4.3.34
* Ubuntu 20, conda 4.9.2
* CentOS 7, conda 4.9.2

**Notes:**  
* The source of the fatal errors turned out not to be the OS, but a change in the way conda is initialized in versions > 4.3
* All software package versions loaded into the conda environment remain unchanged
    * updating the various packages (bioconda, snakemake, etc) will be tracked as a separate issue/task
